version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "01:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "01:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "NuGet"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/src/todo-app.client"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "01:00"
      timezone: "America/Denver"
    commit-message:
      prefix: "npm"
      include: "scope"
