version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/src/todo-app.client"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "GitHub Actions"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "NuGet"
      include: "scope"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
      include: "scope"
