name: todoapidb

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: ${TODO_API_SA_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    ports:
      - "6433:1433"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P \"${TODO_API_SA_PASSWORD}\" -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 13s
      timeout: 3s

  init-db:
    container_name: init-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./db/init.sql:/init.sql:ro
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      /bin/bash -c "
      echo 'Running the init.sql script.';
      /opt/mssql-tools18/bin/sqlcmd -C -S sqlserver -U sa -P '${TODO_API_SA_PASSWORD}' -v varApiPassword='${TODO_API_USER_PASSWORD}' -d master -i /init.sql;
      echo 'All done!';
      "

  flyway:
    container_name: flyway
    image: redgate/flyway:latest
    depends_on:
      init-db:
        condition: service_completed_successfully
      sqlserver:
        condition: service_healthy
    volumes:
      - ./db/migrations:/flyway/migrations:ro
    environment:
      FLYWAY_URL: jdbc:sqlserver://sqlserver:1433;databaseName=TodoApiDb;TrustServerCertificate=True;
      FLYWAY_USER: sa
      FLYWAY_PASSWORD: ${TODO_API_SA_PASSWORD}
      FLYWAY_LOCATIONS: filesystem:./migrations
    command: ["migrate"]
