name: Todo API Web Client CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Node.js CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.3.0
        with:
          global-json-file: global.json

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: src/todo-app.client

      - name: Run Linter
        run: npm run lint
        working-directory: src/todo-app.client

      - name: Prettier Check
        run: npm run pcheck
        working-directory: src/todo-app.client

      - name: Vitest Run
        run: npm run tests
        working-directory: src/todo-app.client

      - name: Build application
        run: npm run build
        working-directory: src/todo-app.client
